### ISSUE TITLE
Are you going to open source the code?

### ISSUE THREAD

**Issue by chikiuso** [baidu-research/deep-voice#1]
Hi Baidu, are you going to open source the project code? Or when will be the commercial tts service available?? thanks.

**Comment by gibiansky** [comment]
We are happy to provide details and answer questions about our paper, techniques, or data, but sadly at this time we can't release open source code for the Deep Voice project. We don't yet have concrete timelines for releasing a commercial TTS service based on this, but it will likely happen eventually.
